#!/usr/bin/env node
/**
 * Generates VERIFICATION.md: a worksheet for upgrading quotations from
 * `corroborated` to `primary` by reading them in the source.
 *
 * Generated rather than hand-kept, so it cannot drift from the content. Rows are
 * ordered by how cheap they are to check: a full text you can open and search
 * costs a minute, a book you have to find costs an afternoon.
 *
 *   node scripts/verification-sheet.mjs
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const EN = join(ROOT, 'src/content/topics/en');

/**
 * How much work a source is to check, and what to do when you open it.
 * Ordered cheapest first; anything unlisted falls to the bottom.
 */
const EFFORT = [
  {
    match: /gutenberg\.org|wikisource\.org|newadvent\.org|law\.justia\.com|dhspriory\.org|russell-j\.com/,
    cost: 1,
    kind: 'Full text, free',
    how: 'Open and search the page for a distinctive phrase.',
  },
  {
    match: /answersingenesis\.org|darwinproject\.ac\.uk|vatican\.va|news\.gallup\.com|preposterousuniverse\.com|reasonablefaith\.org|ctc\.cam\.ac\.uk/,
    cost: 2,
    kind: 'Primary document, free',
    how: 'Open and search the page. Confirm the wording and the date.',
  },
  {
    match: /plato\.stanford\.edu|iep\.utm\.edu/,
    cost: 2,
    kind: 'Reference work, free',
    how: 'Confirms the attribution but not the wording. Repoint at the source text where one exists.',
  },
  {
    match: /philpapers\.org|link\.springer\.com|philarchive\.org/,
    cost: 3,
    kind: 'Scholarly record',
    how: 'The record is free; the text may be paywalled. Check the page number as well as the wording.',
  },
  {
    match: /ucpress\.edu/,
    cost: 3,
    kind: 'Journal of record',
    how: 'Open the article (paywall or library access) and check the page number.',
  },
  {
    match: /simonandschuster\.com|wwnorton\.com|global\.oup\.com|hup\.harvard\.edu/,
    cost: 4,
    kind: 'Book, publisher page only',
    how: 'Needs the book, a library copy, or a searchable scan. Check the page number too.',
  },
];

function effortFor(url) {
  return (
    EFFORT.find((entry) => entry.match.test(url)) ?? {
      cost: 5,
      kind: 'Unclassified',
      how: 'Find the source text and confirm the wording.',
    }
  );
}

/** Every quote in a topic, with the slot it occupies. */
function* quotesOf(topic) {
  for (const side of topic.sides ?? []) {
    for (const argument of side.arguments ?? []) {
      if (argument.quote) yield { slot: `${argument.id} — the claim`, quote: argument.quote };
      if (argument.counter?.quote) {
        yield { slot: `${argument.id} — the objection`, quote: argument.counter.quote };
      }
    }
  }
  for (const item of topic.notes ?? []) {
    if (item.quote) yield { slot: `note: ${item.heading}`, quote: item.quote };
  }
  const context = topic.context;
  if (context?.note?.quote) yield { slot: 'context note', quote: context.note.quote };
  for (const entry of context?.entries ?? []) {
    if (entry.quote) yield { slot: `${entry.id} — positive case`, quote: entry.quote };
    if (entry.onConflict?.quote) {
      yield { slot: `${entry.id} — when evidence disagrees`, quote: entry.onConflict.quote };
    }
    if (entry.standingQuote) yield { slot: `${entry.id} — the reply`, quote: entry.standingQuote };
  }
}

const files = (await readdir(EN)).filter((f) => f.endsWith('.json') && !f.startsWith('_')).sort();
const lines = [];
let total = 0;
let done = 0;

lines.push('# Quotation verification worksheet');
lines.push('');
lines.push('Generated by `node scripts/verification-sheet.mjs`. Do not hand-edit — change');
lines.push('the content files and regenerate.');
lines.push('');
lines.push('Every quotation on this site is published with a `verification` level, shown to');
lines.push('the reader. `corroborated` means the wording was confirmed across several');
lines.push('independent sources but nobody has read it in the original. `primary` means');
lines.push('somebody has.');
lines.push('');
lines.push('The build environment can search the web but cannot open pages, so it cannot');
lines.push('raise anything above `corroborated`. That is what this worksheet is for: each');
lines.push('row is a few minutes in a browser, and confirming one is a single-field edit —');
lines.push('set `verification` to `primary` in every locale file for that quotation, then');
lines.push('run `npm run verify:content` to see the count move.');
lines.push('');
lines.push('Rows are ordered by how cheap they are to check.');
lines.push('');

for (const file of files) {
  const topic = JSON.parse(await readFile(join(EN, file), 'utf8'));
  const rows = [...quotesOf(topic)]
    .map((row) => ({ ...row, effort: effortFor(row.quote.sourceUrl) }))
    .sort((a, b) => a.effort.cost - b.effort.cost || a.slot.localeCompare(b.slot));

  lines.push(`## Topic ${topic.number}: ${topic.title}`);
  lines.push('');
  lines.push(`File: \`src/content/topics/<locale>/${file}\``);
  lines.push('');

  for (const [index, { slot, quote, effort }] of rows.entries()) {
    total += 1;
    if (quote.verification === 'primary') done += 1;

    const status = quote.verification === 'primary' ? 'x' : ' ';
    const isParaphrase = quote.verification === 'paraphrase';
    lines.push(`### ${index + 1}. ${quote.author} — [${status}] ${quote.verification}`);
    lines.push('');
    // A paraphrase is our sentence. Printing it in quotation marks here would be
    // the very mistake the level exists to prevent.
    lines.push(
      isParaphrase
        ? `- **Published as a paraphrase, not a quotation:** ${quote.text}`
        : `- **Published as:** “${quote.text}”`,
    );
    lines.push(`- **Work:** ${quote.work}`);
    lines.push(`- **Year:** ${quote.year}${quote.locator ? ` · ${quote.locator}` : ''}`);
    lines.push(`- **Used for:** ${slot}`);
    lines.push(`- **Source:** ${quote.sourceUrl}`);
    lines.push(
      `- **Verified by:** ${quote.verifiedBy ?? '_(not yet)_'}  ` +
        `**on:** ${quote.verifiedOn ?? '_(not yet)_'}`,
    );
    lines.push(`- **${effort.kind}.** ${effort.how}`);
    lines.push(
      isParaphrase
        ? '- **Check:** whether a real sentence in the source makes this point as well. ' +
          'If one does, replace the paraphrase with it. If none does, confirm the paraphrase ' +
          'is a fair reading and leave the level as it is.'
        : `- **Check:** the wording word for word${
            quote.locator ? `, and that ${quote.locator} is right` : ', and find the page or section'
          }. Confirm it is not quoted out of a sentence that reverses it.`,
    );
    lines.push('');
  }
}

lines.push('---');
lines.push('');
lines.push(`**${done} of ${total} verified against the source text.**`);
lines.push('');
lines.push('When a row is confirmed, set three fields on that quotation in all five locale');
lines.push('files — `verification` to `primary`, `verifiedBy` to who checked it, and');
lines.push('`verifiedOn` to the date — then regenerate this sheet. The record of who checked');
lines.push('and when is the part that makes the claim defensible later; "someone verified');
lines.push('this at some point" is not a defence.');
lines.push('');
lines.push('If the wording turns out to be wrong, fix the text. If it cannot be found at all,');
lines.push('remove the quotation: a missing quotation is a small loss, a wrong one is not.');
lines.push('');

await writeFile(join(ROOT, 'VERIFICATION.md'), lines.join('\n'));
console.log(`VERIFICATION.md written: ${total} quotation(s), ${done} verified.`);
